### ISSUE TITLE
Can't lanch app

### ISSUE THREAD

**Issue by EugeneBogush** [mitshell/corenet#1]
/opt/corenet$ sudo python corenet.py
S1AP: 894 objects loaded into GLOBAL
RRCLTE: 859 objects loaded into GLOBAL_RRCLTE
RRC3G: 4197 objects loaded into GLOBAL_RRC3G
Traceback (most recent call last):
  File "corenet.py", line 232, in <module>
    main()
  File "corenet.py", line 153, in main
    GTPd = GTPUd() # this starts ARPd automatically
  File "/usr/local/lib/python2.7/dist-packages/libmich/mobnet/GTPmgr.py", line 489, in __init__
    self.ext_sk.bind((self.EXT_IF, self.EXT_PROT))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 19] No such device

**Comment by mitshell** [comment]
"socket.error: no such device" means your system did not find the configured interface name on the "internet" side of your core network (self.EXT_IF). Are you sure you configured everything correctly according to https://github.com/mitshell/corenet#basic-configuration ?
